[package]
name = "tasks"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
winapi = { version = "0.3.9", features = ["processthreadsapi", "ntdef", "minwindef", "synchapi"] }