[package]
name = "requests"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.60.2", features = ["Win32_Foundation", "Win32_Networking_WinHttp"] }
json = { path = "../json" }