[package]
name = "browsers"
version = "0.1.0"
edition = "2024"

[dependencies]
tasks = { path = "../../tasks" }
utils = { path = "../../utils" }
sqlite = { path = "../../sqlite" }
json = { path = "../../json" }
obfstr = "0.4.4"
