[package]
name = "games"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { workspace = true }
filesystem = { path = "../../filesystem" }
collector = { path = "../../collector" }
obfstr = "0.4.4"
tasks = { path = "../../tasks" }
regedit = { path = "../../regedit" }