[package]
name = "code-vm"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", default-features = false, features = ["std_rng"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
