[package]
name = "ipinfo"
version = "0.1.0"
edition = "2024"

[dependencies]
requests = { path = "../requests" }
json = { path = "../json" }
utils = { path = "../utils" }
obfstr = "0.4.4"
indoc = "2.0.6"